/*
 * Copyright 2025, UNSW
 * SPDX-License-Identifier: BSD-2-Clause
 */

#pragma once


#define MULTIPLEXER_CLIENT_NUM  2

#define MULTIPLEXER_WORKER_TRHEAD_NUM   MULTIPLEXER_CLIENT_NUM
#define MULTIPLEXER_THREAD_NUM          (MULTIPLEXER_WORKER_TRHEAD_NUM + 1)
#define MULTIPLEXER_WORKER_TRHEAD_STACKSIZE 0x40000
