PAGE_SIZE = 0x1000

LOADER_CONTEXT_BASE = 0x0FF40000
LOADER_CONTEXT_SIZE = PAGE_SIZE

OSSVC_METADATA_BASE = 0x0FF80000
OSSVC_METADATA_SIZE = PAGE_SIZE

LOADER_METADATA_BASE = 0x0FFC0000
LOADER_METADATA_SIZE = PAGE_SIZE

LOADER_PROGRAM_BASE = 0x10000000
LOADER_PROGRAM_SIZE = 0x00800000

TRAMPOLINE_IMAGE_BASE = 0x30000000
TRAMPOLINE_IMAGE_SIZE = 0x00800000

CONTAINER_IMAGE_BASE = 0x50000000
CONTAINER_IMAGE_SIZE = 0x00800000

VM_REGIONS = [
    {
        "name": "LOADER_CONTEXT",
        "base": LOADER_CONTEXT_BASE,
        "size": LOADER_CONTEXT_SIZE,
    },
    {
        "name": "OSSVC_METADATA",
        "base": OSSVC_METADATA_BASE,
        "size": OSSVC_METADATA_SIZE,
    },
    {
        "name": "LOADER_METADATA",
        "base": LOADER_METADATA_BASE,
        "size": LOADER_METADATA_SIZE,
    },
    {
        "name": "LOADER_PROGRAM",
        "base": LOADER_PROGRAM_BASE,
        "size": LOADER_PROGRAM_SIZE,
    },
    {
        "name": "TRAMPOLINE_IMAGE",
        "base": TRAMPOLINE_IMAGE_BASE,
        "size": TRAMPOLINE_IMAGE_SIZE,
    },
    {
        "name": "CONTAINER_IMAGE",
        "base": CONTAINER_IMAGE_BASE,
        "size": CONTAINER_IMAGE_SIZE,
    },
]
